---
jobs:
  - name: build-tw-cd-concourse-ci
    plan:
      - get: scripts
        trigger: false
      - get: tw-cd-concourse-ci-source
        trigger: true
      - get: tw-cd-concourse-ci-version
        params: {bump: minor}
      - put: tw-cd-concourse-ci
        params:
          build: tw-cd-concourse-ci-source/Dockerfiles/tw-cd-concourse-ci
          tag: tw-cd-concourse-ci-version/number
          tag_as_latest: true
      - put: tw-cd-concourse-ci-version
        params: {bump: minor}

resources:
  - name: scripts
    type: git
    source:
      uri: {{scripts_git_uri}}
      branch: {{scripts_git_branch}}
      private_key: {{scripts_git_private_key}}
  - name: tw-cd-concourse-ci-source
    type: git
    source:
      uri: {{scripts_git_uri}}
      branch: {{scripts_git_branch}}
      private_key: {{scripts_git_private_key}}
      paths:
        - Dockerfiles/tw-cd-concourse-ci/*
  - name: tw-cd-concourse-ci
    type: docker-image
    source:
      repository: 406465642840.dkr.ecr.ap-southeast-2.amazonaws.com/tw-cd-concourse-ci
  - name: tw-cd-concourse-ci-version
    type: semver
    source:
      initial_version: 1.0.0
      driver: git
      uri: {{versions_git_uri}}
      branch: {{versions_git_branch}}
      private_key: {{versions_git_private_key}}
      file: tw-cd-concourse-ci

